// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebVersionStore.Models.Database
{
    public partial class RepositoryAccessLevelsResult
    {
        public Guid RepositoryId { get; set; }
        public string UserId { get; set; }
        public bool? IsAuthor { get; set; }
        public bool? CanView { get; set; }
        public bool? CanAdd { get; set; }
        public bool? CanRemove { get; set; }
        public bool? CanEdit { get; set; }
    }
}
