// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebVersionStore.Models.Database;

public partial class User
{
    public string Login { get; set; }

    public string Password { get; set; }

    public string Username { get; set; }

    public virtual ICollection<Repository> Repositories { get; set; } = new List<Repository>();

    public virtual ICollection<UserRepositoryAccess> UserRepositoryAccesses { get; set; } = new List<UserRepositoryAccess>();
}