// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using WebVersionStore.Models.Database;

namespace WebVersionStore.Models.Database
{
    public partial class WebVersionControlContext
    {

        [DbFunction("RepositoryAccessLevels", "dbo")]
        public IQueryable<RepositoryAccessLevelsResult> RepositoryAccessLevels(Guid? repo)
        {
            return FromExpression(() => RepositoryAccessLevels(repo));
        }

        [DbFunction("UserAccessLevel", "dbo")]
        public IQueryable<UserAccessLevelResult> UserAccessLevel(string user, Guid? repo)
        {
            return FromExpression(() => UserAccessLevel(user, repo));
        }

        [DbFunction("UserAccessLevels", "dbo")]
        public IQueryable<UserAccessLevelsResult> UserAccessLevels(string user)
        {
            return FromExpression(() => UserAccessLevels(user));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RepositoryAccessLevelsResult>().HasNoKey();
            modelBuilder.Entity<UserAccessLevelResult>().HasNoKey();
            modelBuilder.Entity<UserAccessLevelsResult>().HasNoKey();
        }
    }
}
